FROM amazon/aws-sam-cli-build-image-ruby2.7

# Ensure minimum required SAM version.
ENV SAM_CLI_VERSION=1.23.0
RUN curl -L "https://github.com/aws/aws-sam-cli/releases/download/v${SAM_CLI_VERSION}/aws-sam-cli-linux-x86_64.zip" \
         -o "aws-sam-cli-linux-x86_64.zip" && \
    unzip -q aws-sam-cli-linux-x86_64.zip -d sam-installation && \
    ./sam-installation/install && \
    rm -rf ./sam-installation ./aws-sam-cli-linux-x86_64.zip

# Node for JavaScript.
RUN curl -sL https://rpm.nodesource.com/setup_14.x | bash - && \
    yum install -y nodejs && \
    curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo && \
    rpm --import https://dl.yarnpkg.com/rpm/pubkey.gpg && \
    yum install -y yarn

WORKDIR /var/task
