#!/usr/bin/env bash
set -e

# Clean any previous bundle/builds.
rm -rf ./.aws-sam/build

# Ensure native extensions built for platform.
sam build --use-container

# [HOOK] Environments & Configuration
# https://lamby.custominktech.com/docs/environment_and_configuration

# [HOOK] Asset Hosts & Precompiling
# https://lamby.custominktech.com/docs/asset_host_and_precompiling

# Clean un-needed artifacts.
pushd ./.aws-sam/build/RailsFunction/
rm -rf .aws-sam \
  .git \
  log \
  test \
  tmp
popd
