name: Release Gem
on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: bundle install

      - name: Build gem
        run: gem build lamby.gemspec

      - name: Upload gem artifact
        uses: actions/upload-artifact@v4
        with:
          name: lamby-gem
          path: ./lamby-*.gem

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download gem artifact
        uses: actions/download-artifact@v6
        with:
          name: lamby-gem

      - name: Publish gem
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: gem push ./lamby-*.gem