name: Release Gem
on:
  workflow_dispatch:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup & Release
        uses: devcontainers/ci@v0.3
        with:
          push: never
          cacheFrom: ghcr.io/rails-lambda/lamby-devcontainer
          env:
            RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          runCmd: |
            ./bin/setup
            ./bin/release